### ISSUE TITLE
defining a second database connection does not work

### ISSUE THREAD

**Issue by fritzmg** [contao/manager-bundle#43]
## Reproduction

1. create an `app/config/config.yml` with
```yml
doctrine:
    dbal:
        connections:
            second:
                driver:   pdo_mysql
                host:     '%second_database_host%'
                port:     '%second_database_port%'
                dbname:   '%second_database_name%'
                user:     '%second_database_user%'
                password: '%second_database_password%'
                charset:  UTF8
```
2. provide the database parameters in your `app/config/parameters.yml`
```yml
parameters:
    …
    second_database_host: …
    second_database_port: …
    second_database_user: …
    second_database_password: …
    second_database_name: …
```
3. try to access the second database connection with
```php
\System::getContainer()->get('doctrine')->getConnection('second');
```
The following error will occur:
```
Doctrine ORM Connection named "second" does not exist.
```
Same with
```php
\System::getContainer()->get('doctrine.dbal.second_connection');
```
»
```
You have requested a non-existent service "doctrine.dbal.second_connection". Did you mean this: "doctrine.dbal.default_connection"?
```
